from rest_framework import serializers 
from unitelegale.models import Unitelegale
 
 
class UnitelegaleSerializer(serializers.ModelSerializer):
 
    class Meta:
        model = Unitelegale
        fields = ('id',
                    'siren',
                    'dateFin',
                    'dateDebut',
                    'etatAdministratifUniteLegale',
                    'changementEtatAdministratifUniteLegale',
                    'nomUniteLegale',
                    'changementNomUniteLegale',
                    'nomUsageUniteLegale',
                    'changementNomUsageUniteLegale',
                    'denominationUniteLegale',
                    'changementDenominationUniteLegale',
                    'denominationUsuelle1UniteLegale',
                    'denominationUsuelle2UniteLegale',
                    'denominationUsuelle3UniteLegale',
                    'changementDenominationUsuelleUniteLegale',
                    'categorieJuridiqueUniteLegale',
                    'changementCategorieJuridiqueUniteLegale',
                    'activitePrincipaleUniteLegale',
                    'nomenclatureActivitePrincipaleUniteLegale',
                    'changementActivitePrincipaleUniteLegale',
                    'nicSiegeUniteLegale',
                    'changementNicSiegeUniteLegale',
                    'economieSocialeSolidaireUniteLegale',
                    'changementEconomieSocialeSolidaireUniteLegale',
                    'caractereEmployeurUniteLegale',
                    'changementCaractereEmployeurUniteLegale',
                    'statutDiffusionUniteLegale',
                    'unitePurgeeUniteLegale',
                    'dateCreationUniteLegale',
                    'sigleUniteLegale',
                    'sexeUniteLegale',
                    'prenom1UniteLegale',
                    'prenom2UniteLegale',
                    'prenom3UniteLegale',
                    'prenom4UniteLegale',
                    'prenomUsuelUniteLegale',
                    'pseudonymeUniteLegale',
                    'identifiantAssociationUniteLegale',
                    'trancheEffectifsUniteLegale',
                    'anneeEffectifsUniteLegale',
                    'dateDernierTraitementUniteLegale',
                    'nombrePeriodesUniteLegale',
                    'categorieEntreprise',
                    'anneeCategorieEntreprise',
                    'etatAdministratifUniteLegale')
