# Generated by Django 3.1.5 on 2021-01-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitelegale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitelegale',
            old_name='dateDebut',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='unitelegale',
            old_name='dateFin',
            new_name='date_fin',
        ),
    ]
