# Generated by Django 3.1.5 on 2021-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitelegale', '0003_auto_20210117_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitelegale',
            name='etatAdministratifUniteLegale',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
